export const QUERY_KEYS = {
  FETCH_PAYMENT_CARDS: 'FETCH_PAYMENT_CARDS',
  GENERATE_VERIFY_USER_CODE: 'GENERATE_VERIFY_USER_CODE',
  FETCH_GENERATION_HISTORY: 'FETCH_GENERATION_HISTORY',
  GENERATION_IMAGE_DETAILS: 'GENERATION_IMAGE_DETAILS',
  FETCH_EXAMPLES: 'FETCH_EXAMPLES',
};
