export const LOADING_FACTS = [
  'Cakes have been around for centuries, with their origins dating back to ancient civilizations.',
  "The word 'cake' comes from the Old Norse word 'kaka.'",
  'The earliest cakes were more like bread and often sweetened with honey.',
  'The concept of frosting or icing on cakes began in the 17th century.',
  "The world's largest cake weighed over 15,032 pounds and was made in 2004.",
  'The most expensive cake ever made was worth over $75 million and was adorned with diamonds.',
  'Cakes come in a wide variety of flavors, from chocolate and vanilla to red velvet and carrot cake.',
  'Angel food cake is known for being light and fluffy, made primarily from egg whites and sugar.',
  'Pound cake got its name from the original recipe, which called for a pound each of butter, sugar, eggs, and flour.',
  "The world's tallest cake ever made was over 108 feet tall.",
  'Cakes are often associated with celebrations, such as birthdays, weddings, and anniversaries.',
  'The tradition of having a wedding cake dates back to ancient Rome.',
  'Red velvet cake gets its distinctive color from cocoa and buttermilk.',
  'The Great British Bake Off is a popular TV show entirely dedicated to baking, including cakes.',
  'The Guinness World Record for the most cupcakes baked in one hour is over 2,344.',
  'Chocolate cake is one of the most popular cake flavors in the world.',
  'The Black Forest cake, a famous German dessert, is made with layers of chocolate sponge cake, whipped cream, and cherries.',
  'The concept of birthday candles on a cake comes from ancient Greece, where people would make a wish to the goddess Artemis.',
  "In some cultures, breaking a cake over a bride's head is considered good luck at weddings.",
  'Ice cream cakes combine the goodness of cake and ice cream in one delicious dessert.',
  "A 'bundt' cake is baked in a distinctive ring-shaped pan.",
  'Carrot cake is often believed to have originated from medieval Europe.',
  'Cakes can be made in countless shapes and sizes, from traditional round and square cakes to novelty designs.',
  "The first cupcakes were baked in the 19th century and were often called 'number cakes.'",
  'Lava cakes are known for their molten chocolate center that oozes when cut.',
  "In Japan, it's a tradition to give and receive 'Christmas cakes,' which are sponge cakes decorated with strawberries and whipped cream.",
  'Marble cake is created by swirling together vanilla and chocolate cake batters.',
  'Tiramisu, an Italian dessert, features layers of coffee-soaked ladyfingers and mascarpone cheese.',
  'Cakes can be decorated in various ways, from fondant sculptures to intricate piping designs.',
  "The world's most massive cupcake weighed over 1,176.6 pounds.",
  'Cakes have become a popular subject for food photography and social media posts.',
];

export const DESIGN_TYPES = [
  {
    code: 0,
    label: 'Simple',
    price: '450-800 SAR',
  },
  {
    code: 1,
    label: 'Normal',
    price: '801-1500 SAR',
  },
  {
    code: 2,
    label: 'Complex',
    price: '1501-5000 SAR',
  },
  // {
  //   code: 3,
  //   label: 'Royal',
  //   price: '>5000 SAR',
  // },
];
